### ISSUE TITLE
click on continue without password crashes the app while Restore a Backup file

### ISSUE THREAD

**Issue by kr-nahid** [MCMrARM/revolution-irc#134]
#### Expected behavior
it shouldn't crash when i click on continue without password for **Restore a Backup** .

#### Actual behavior
for **Restore a Backup** i select  file from **Google Drive** and when i click on continue without password crashes the app .

#### How to reproduce
* download the app and run it 
* click on (+) and Add a new server
* then go to settings and click on Backup and click on **Create a new Backup** and save it to your Google Drive with password

* then try to restore without password
* and note the bug.

> Browser/App version: Revolution Irc V0.3.2
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=AogE81y9MiQ

**Comment by tobias-g1** [comment]
Replicated on Android 6.0
```
    --------- beginning of crash
05-27 13:10:43.886 7274-7306/io.mrarm.irc E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: io.mrarm.irc, PID: 7274
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException
        at net.lingala.zip4j.core.ZipFile.setPassword(ZipFile.java:650)
        at io.mrarm.irc.config.BackupManager.restoreBackup(BackupManager.java:140)
        at io.mrarm.irc.setup.BackupProgressActivity$RestoreTask.doInBackground(BackupProgressActivity.java:234)
        at io.mrarm.irc.setup.BackupProgressActivity$RestoreTask.doInBackground(BackupProgressActivity.java:217)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```
