### ISSUE TITLE
Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

### ISSUE THREAD

**Issue by emersion** [MCMrARM/revolution-irc#248]
1. Join a channel on a bouncer via Revolution IRC
2. Disconnect
3. From another client, join another channel
4. Start Revolution IRC, crashes when the server is selected

```
03-16 09:40:16.140 12947 12947 I ChatMessagesFragment: Request status message list
03-16 09:40:16.141 12947 12947 I ChatMessagesFragment: Got server status message list: 6 messages
03-16 09:40:16.141 12947 12947 I ChatMessagesFragment: Request message list for: #caduc
03-16 09:40:16.141 12947 12947 I ChatMessagesFragment: Got channel info #caduc
03-16 09:40:16.144 12947 12978 E SQLiteLog: (1) no such table: messages_#caduc in "SELECT _id,sender_data,sender_uuid,date,text,type,extra FROM 'messages_#caduc' WHERE type!=-1 ORDER BY _id DESC LIMIT 89"
03-16 09:40:16.163 12947 12978 I chatty  : uid=10127(io.mrarm.irc) pool-2-thread-1 identical 13 lines
03-16 09:40:16.164 12947 12978 E SQLiteLog: (1) no such table: messages_#caduc in "SELECT _id,sender_data,sender_uuid,date,text,type,extra FROM 'messages_#caduc' WHERE type!=-1 ORDER BY _id DESC LIMIT 89"
03-16 09:40:16.165 12947 12978 I ChatMessagesFragment: Got message list for #caduc: 11 messages
03-16 09:40:05.452 12587 12587 I google_charger: l=98 vb=4391 vc=4391 c=-338 fv=4400000 t=250 s=Fast usb=1 wlc=0
03-16 09:40:16.194   880   880 I android.hardware.health@2.0-service.bonito: capacity: 3035243
03-16 09:40:05.456   880   880 W healthd : battery l=98 v=4391 t=25.0 h=2 st=2 c=338 fc=3035243 cc=16 chg=u
03-16 09:40:16.203 12947 12947 D AndroidRuntime: Shutting down VM
03-16 09:40:16.205 12947 12947 E AndroidRuntime: FATAL EXCEPTION: main
03-16 09:40:16.205 12947 12947 E AndroidRuntime: Process: io.mrarm.irc, PID: 12947
03-16 09:40:16.205 12947 12947 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.text.SpannableString.<init>(SpannableString.java:34)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.text.SpannableString.<init>(SpannableString.java:43)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at io.mrarm.irc.util.IRCColorUtils.getFormattedString(IRCColorUtils.java:132)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at io.mrarm.irc.util.MessageBuilder.buildMessage(MessageBuilder.java:372)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at io.mrarm.irc.chat.ChatMessagesAdapter$MessageHolder.bind(ChatMessagesAdapter.java:437)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at io.mrarm.irc.chat.ChatMessagesAdapter.onBindViewHolder(ChatMessagesAdapter.java:280)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:587)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1102)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1102)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1102)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.View.layout(View.java:22471)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:729)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:955)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:903)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7396)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-16 09:40:16.205 12947 12947 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:949)
03-16 09:40:16.207  1329 14905 W ActivityTaskManager:   Force finishing activity io.mrarm.irc/.MainActivity
```

**Comment by emersion** [comment]
Thanks for the fix!
