### ISSUE TITLE
Crashing when loading channels from ZNC bouncer

### ISSUE THREAD

**Issue by goldmund256** [MCMrARM/revolution-irc#335]
**Device**: Google Pixel 6a
**OS**: GrapheneOS
**Installed via**: F-Droid

Revolution-irc crashes when channels from my ZNC bouncer server are loaded.

My ZNC instance uses the [clientbuffer](https://wiki.znc.in/Clientbuffer) module which maintains specific buffers for identified clients. For Revolution-irc to identify itself on ZNC, my password has the following structure: `username@identifier/network:password`

Revolution-irc does NOT crash when the clientbuffer module isn't used, i.e. when password `username/network:password` is used. Obviously, I miss out on the function of the _clientbuffer_ module.

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221105.002/2022111000:user/release-keys
package: io.mrarm.irc:12
process: io.mrarm.irc

java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 69
at java.lang.String.checkBoundsBeginEnd(String.java:3942)
at java.lang.String.substring(String.java:2467)
at io.mrarm.chatlib.irc.MessageHandler.handleLine(MessageHandler.java:25)
at io.mrarm.chatlib.irc.IRCConnection.handleInput(IRCConnection.java:120)
at io.mrarm.chatlib.irc.IRCConnection.lambda$WaOIvzbB9flSh3k_2YttU9UsnDA(Unknown Source:0)
at io.mrarm.chatlib.irc.-$$Lambda$IRCConnection$WaOIvzbB9flSh3k_2YttU9UsnDA.run(Unknown Source:2)
at java.lang.Thread.run(Thread.java:1012)
```

**Comment by goldmund256** [comment]
The last release (0.5.5) has fixed this issue. Closing.
